---
# tasks file for myapache
- package: 
    name: httpd
    state: present
- file: 
    path: /var/www/html/webpages
    state: directory
- template:
    src: index.html
    dest: /var/www/html/webpages/index.html
- service:
    name: httpd
    state: restarted
